# Generated by Django 4.0.5 on 2022-06-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('codigoEspecialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Especialidad', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Especialidades_1',
                'db_table': 'especialidadess',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TipoUsuario', models.BooleanField(choices=[(True, 'Medico'), (False, 'Administrador')], default=True, verbose_name='Tipo de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.CharField(default=1, max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nombreUsuario', models.CharField(max_length=10)),
                ('contrasenaUsuario', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField(blank=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.BooleanField(choices=[(True, 'Masculino'), (False, 'Femenino')], verbose_name='Genero')),
                ('especialidadess', models.ManyToManyField(to='libreria.especialidades')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.usuario')),
            ],
            options={
                'verbose_name': 'Medico_1',
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(default=1, max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nombreUsuario', models.CharField(max_length=10)),
                ('contrasenaUsuario', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField(blank=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.BooleanField(choices=[(True, 'Masculino'), (False, 'Femenino')], verbose_name='Genero')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.usuario')),
            ],
            options={
                'verbose_name': 'Administrador_1',
                'db_table': 'Administrador',
            },
        ),
    ]
