# Generated by Django 4.0.5 on 2022-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('rutPaciente', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombrePaciente', models.CharField(max_length=15)),
                ('apellidoPaciente', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField(blank=True)),
                ('genero', models.BooleanField(choices=[(True, 'Masculino'), (False, 'Femenino')], verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Paciente_1',
                'db_table': 'Paciente__1',
            },
        ),
    ]
