# Generated by Django 4.0.5 on 2022-06-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_pacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atenciones',
            fields=[
                ('idAtencion', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=200)),
                ('anamnesis', models.CharField(max_length=200)),
                ('fechaAtencion', models.DateField(blank=True)),
                ('hora', models.TimeField()),
                ('sala', models.CharField(max_length=25)),
                ('rutMedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreria.medico')),
                ('rutPaciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreria.pacientes')),
            ],
        ),
    ]
